// Copyright 2019-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_present_wait.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2019-05-15
*IP Status*::
    No known IP claims.
*Contributors*::
  - Keith Packard, Valve
  - Ian Elliott, Google
  - Tobias Hector, AMD
  - Daniel Stone, Collabora

=== Description

This device extension allows an application that uses the
`apiext:VK_KHR_swapchain` extension to wait for present operations to
complete.
An application can use this to monitor and control the pacing of the
application by managing the number of outstanding images yet to be
presented.

include::{generated}/interfaces/VK_KHR_present_wait.adoc[]

=== Issues

1) When does the wait finish?

*RESOLVED*.
The wait will finish when the present is visible to the user.
There is no requirement for any precise timing relationship between the
presentation of the image to the user, but implementations should: signal
the wait as close as possible to the presentation of the first pixel in the
new image to the user.

2) Should this use fences or other existing synchronization mechanism.

*RESOLVED*.
Because display and rendering are often implemented in separate drivers,
this extension will provide a separate synchronization API.

3) Should this extension share present identification with other extensions?

*RESOLVED*.
Yes.
A new extension, VK_KHR_present_id, should be created to provide a shared
structure for presentation identifiers.

4) How should the implementation handle `presentId` ordering and "very old" IDs?

*RESOLVED*

Because `presentId` values are provided by the application and are not required to be monotonic, the implementation cannot rely on "less than or equal to" logic to determine completion.

The implementation **should** maintain a record of all `presentId` values currently in-flight (i.e., those that have been queued via `vkQueuePresentKHR` but have not yet been retired by the presentation engine).

* If a `vkWaitForPresent2KHR` call references a `presentId` that is currently in-flight, the call must block until that specific presentation completes or the timeout expires.

* If the `presentId` is not currently in-flight, the implementation must return `VK_SUCCESS` immediately.

> [!NOTE]
> This behavior implies that both "already presented" IDs and "random/never-existed" IDs result in an immediate `VK_SUCCESS`. This avoids the requirement for drivers to maintain an exhaustive, ever-growing history of all previously presented IDs.
> 

=== Examples

=== Version History

  * Revision 1, 2019-02-19 (Keith Packard)
  ** Initial version
